### ISSUE TITLE
Language Server errors

### ISSUE THREAD

**Issue by dionoid** [zeh/vscode-dasm#2]
Hi, after installing the extension, I get this error in the output screen:

Error! Trying to include "undefined" as a assembly file dependency without contents!
Error! Trying to include "undefined" as a assembly file dependency without contents!
c:\Users\dion\.vscode\extensions\zehfernando.vscode-dasm-4.0.0\out\server\node_modules\dasm\lib\index.js:79
                        address = parseNumber(rawLine.match(addressFind)[1]);
                                                                        ^

TypeError: Cannot read property '1' of null
    at c:\Users\dion\.vscode\extensions\zehfernando.vscode-dasm-4.0.0\out\server\node_modules\dasm\lib\index.js:79:73
    at Array.forEach (<anonymous>)
    at parseList (c:\Users\dion\.vscode\extensions\zehfernando.vscode-dasm-4.0.0\out\server\node_modules\dasm\lib\index.js:38:14)
    at Object.default_1 [as default] (c:\Users\dion\.vscode\extensions\zehfernando.vscode-dasm-4.0.0\out\server\node_modules\dasm\lib\index.js:459:27)
    at Object.assemble (c:\Users\dion\.vscode\extensions\zehfernando.vscode-dasm-4.0.0\out\server\src\providers\Assembler.js:6:34)
    at Project.assemble (c:\Users\dion\.vscode\extensions\zehfernando.vscode-dasm-4.0.0\out\server\src\project\Project.js:70:49)
    at Project._files.onChanged.add (c:\Users\dion\.vscode\extensions\zehfernando.vscode-dasm-4.0.0\out\server\src\project\Project.js:12:18)
    at c:\Users\dion\.vscode\extensions\zehfernando.vscode-dasm-4.0.0\out\server\node_modules\simplesignal\dist\SimpleSignal.commonjs.js:43:18
    at Array.forEach (<anonymous>)
    at SimpleSignal.dispatch (c:\Users\dion\.vscode\extensions\zehfernando.vscode-dasm-4.0.0\out\server\node_modules\simplesignal\dist\SimpleSignal.commonjs.js:42:28)
[Info  - 11:39:49 AM] Connection to server got closed. Server will restart.

**Comment by zeh** [comment]
Hey @dionoid. Thanks for this feedback (and #3). I'm sorry I haven't seen this earlier. I'm taking a look.

**Comment by acejacek** [comment]
I'm having the same error when DASM's `echo` exists in code:
```txt
   lda #5 
   sta $80
   echo "end of compile"
```

Full error log:

```text
Error! Trying to include "undefined" as a assembly file dependency without contents!
/Users/acejacek/.vscode/extensions/zehfernando.vscode-dasm-4.0.0/out/server/node_modules/dasm/lib/index.js:79
                        address = parseNumber(rawLine.match(addressFind)[1]);
                                                                        ^

TypeError: Cannot read property '1' of null
    at /Users/acejacek/.vscode/extensions/zehfernando.vscode-dasm-4.0.0/out/server/node_modules/dasm/lib/index.js:79:73
    at Array.forEach (<anonymous>)
    at parseList (/Users/acejacek/.vscode/extensions/zehfernando.vscode-dasm-4.0.0/out/server/node_modules/dasm/lib/index.js:38:14)
    at Object.default_1 [as default] (/Users/acejacek/.vscode/extensions/zehfernando.vscode-dasm-4.0.0/out/server/node_modules/dasm/lib/index.js:459:27)
    at Object.assemble (/Users/acejacek/.vscode/extensions/zehfernando.vscode-dasm-4.0.0/out/server/src/providers/Assembler.js:6:34)
    at Project.assemble (/Users/acejacek/.vscode/extensions/zehfernando.vscode-dasm-4.0.0/out/server/src/project/Project.js:70:49)
    at /Users/acejacek/.vscode/extensions/zehfernando.vscode-dasm-4.0.0/out/server/src/project/Project.js:12:18
    at /Users/acejacek/.vscode/extensions/zehfernando.vscode-dasm-4.0.0/out/server/node_modules/simplesignal/dist/SimpleSignal.commonjs.js:43:18
    at Array.forEach (<anonymous>)
    at SimpleSignal.dispatch (/Users/acejacek/.vscode/extensions/zehfernando.vscode-dasm-4.0.0/out/server/node_modules/simplesignal/dist/SimpleSignal.commonjs.js:42:28)
```
